<?php

return array(
    'aclManager'   => array(
        'class' => 'Acl_Manager',
                                    ),    'aclProviderManager'   => array(
        'class' => 'Acl_Provider_Manager',
                                    ),    'aclProviderTable'   => array(
        'class' => 'Acl_Manager/aclProvider',
                        'args'  => array(
                        'Table'                    ),
                                'source'    => array(
                        'name'  => 'aclProviderManager',
                        'method'    => 'get',
                                )
            ),    'aclRole'   => array(
        'class' => 'Acl_Role',
                                    ),    'activation'   => array(
        'class' => 'Activation',
                                    ),    'annotationModelManager'   => array(
        'class' => 'Annotation_Model_Manager',
                                    ),    'apiCommandManager'   => array(
        'class' => 'Api_Command_Manager',
                                    ),    'apiConnectorManager'   => array(
        'class' => 'Api_Connector_Manager',
                                    ),    'apiError'   => array(
        'class' => 'Api_Error',
                                    ),    'apiManager'   => array(
        'class' => 'Api_Manager',
                                    ),    'apiTransportManager'   => array(
        'class' => 'Api_Transport_Manager',
                                    ),    'attributeManager'   => array(
        'class' => 'Attribute_Manager',
                                    ),    'authorization'   => array(
        'class' => 'Authorization',
                                    ),    'authorizationLog'   => array(
        'class' => 'Authorization_Log',
                                    ),    'authorizationLoginzaToken'   => array(
        'class' => 'Authorization_Loginza_Token',
                                    ),    'breadCrumb'   => array(
        'class' => 'Bread_Crumb',
                                    ),    'cacheBlockManager'   => array(
        'class' => 'Cache_Block_Manager',
                                    ),    'cacheBlockSpecificationManager'   => array(
        'class' => 'Cache_Block_Specification_Manager',
                                    ),    'cacheManager'   => array(
        'class' => 'Cache_Manager',
                                    ),    'collectionManager'   => array(
        'class' => 'Model_Collection_Manager',
                                    ),    'configManager'   => array(
        'class' => 'Config_Manager',
                                    ),    'controllerActionModifierManager'   => array(
        'class' => 'Controller_Action_Modifier_Manager',
                                    ),    'controllerDispatcher'   => array(
        'class' => 'Controller_Dispatcher',
                                    ),    'controllerFrontStrategyManager'   => array(
        'class' => 'Controller_Front_Strategy_Manager',
                                    ),    'controllerManager'   => array(
        'class' => 'Controller_Manager',
                                    ),    'controllerTagManager'   => array(
        'class' => 'Controller_Tag_Manager',
                                    ),    'controllerValidatorExceptionManager'   => array(
        'class' => 'Controller_Validator_Exception_Manager',
                                    ),    'controllerValidatorManager'   => array(
        'class' => 'Controller_Validator_Manager',
                                    ),    'createClassStrategyManager'   => array(
        'class' => 'Create_Class_Strategy_Manager',
                                    ),    'cryptManager'   => array(
        'class' => 'Crypt_Manager',
                                    ),    'dataDriverManager'   => array(
        'class' => 'Data_Driver_Manager',
                                    ),    'dataFilterManager'   => array(
        'class' => 'Data_Filter_Manager',
                                    ),    'dataProviderBlock'   => array(
        'class' => 'View_Cache_Fragment_Manager/provider',
                        'args'  => array(
                        'Block'                    ),
                                'source'    => array(
                        'name'  => 'dataProviderManager',
                        'method'    => 'get',
                                )
            ),    'dataProviderFile'   => array(
        'class' => 'Helper_Migration_Sequence/provider',
                        'args'  => array(
                        'File'                    ),
                                'source'    => array(
                        'name'  => 'dataProviderManager',
                        'method'    => 'get',
                                )
            ),    'dataProviderManager'   => array(
        'class' => 'Data_Provider_Manager',
                                    ),    'dataSchemeManager'   => array(
        'class' => 'Data_Scheme_Manager',
                                    ),    'dataSource'   => array(
        'class' => 'Data_Source',
                                    ),    'dataSourceManager'   => array(
        'class' => 'Data_Source_Manager',
                                    ),    'dataTransportManager'   => array(
        'class' => 'Data_Transport_Manager',
                                    ),    'dataValidator'   => array(
        'class' => 'Data_Validator',
                                    ),    'dataValidatorManager'   => array(
        'class' => 'Data_Validator_Manager',
                                    ),    'dds'   => array(
        'class' => 'DDS',
                                    ),    'debug'   => array(
        'class' => 'Debug',
                                    ),    'device'   => array(
        'class' => 'Device',
                                    ),    'dto'   => array(
        'class' => 'Dto',
                                    ),    'errorRender'   => array(
        'class' => 'Error_Render',
                                    ),    'eventManager'   => array(
        'class' => 'Event_Manager',
                                    ),    'executor'   => array(
        'class' => 'Executor',
                                    ),    'formBuilder'   => array(
        'class' => 'Form_Builder',
                                        'source'    => array(
                        'method'    => 'instance',
                                )
            ),    'geoDistanceCalculator'   => array(
        'class' => 'Geo_Distance_Calculator',
                                    ),    'helperActivation'   => array(
        'class' => 'Helper_Activation',
                                    ),    'helperAdminRedirect'   => array(
        'class' => 'Helper_Admin_Redirect',
                                    ),    'helperAdminUser'   => array(
        'class' => 'Helper_Admin_User',
                                    ),    'helperAnnotation'   => array(
        'class' => 'Helper_Annotation',
                                    ),    'helperAnnotationGenerator'   => array(
        'class' => 'Helper_Annotation_Generator',
                                    ),    'helperAnnotationModel'   => array(
        'class' => 'Helper_Annotation_Model',
                                'disableConstruct'      => true,
                    ),    'helperAnnotationModelField'   => array(
        'class' => 'Helper_Annotation_Model_Field',
                                'disableConstruct'      => true,
                    ),    'helperAnnotationOrm'   => array(
        'class' => 'Helper_Annotation_Orm',
                                    ),    'helperAnnotationSchedule'   => array(
        'class' => 'Helper_Annotation_Schedule',
                                    ),    'helperApi'   => array(
        'class' => 'Helper_Api',
                                    ),    'helperArray'   => array(
        'class' => 'Helper_Array',
                                    ),    'helperBehavior'   => array(
        'class' => 'Helper_Behavior',
                                    ),    'helperClass'   => array(
        'class' => 'Helper_Class',
                                    ),    'helperCli'   => array(
        'class' => 'Helper_Cli',
                                    ),    'helperCliProgressBar'   => array(
        'class' => 'Helper_Cli_Progress_Bar',
                                    ),    'helperCodeGenerator'   => array(
        'class' => 'Helper_Code_Generator',
                                    ),    'helperCompile'   => array(
        'class' => 'Helper_Compile',
                                    ),    'helperComponent'   => array(
        'class' => 'Helper_Component',
                                    ),    'helperConverter'   => array(
        'class' => 'Helper_Converter',
                                    ),    'helperCsv'   => array(
        'class' => 'Helper_Csv',
                                    ),    'helperDate'   => array(
        'class' => 'Helper_Date',
                                    ),    'helperEmail'   => array(
        'class' => 'Helper_Email',
                                    ),    'helperEnv'   => array(
        'class' => 'Helper_Env',
                                    ),    'helperEvent'   => array(
        'class' => 'Helper_Event',
                                    ),    'helperFile'   => array(
        'class' => 'Helper_File',
                                    ),    'helperGeoIP'   => array(
        'class' => 'Helper_GeoIP',
                                    ),    'helperHash'   => array(
        'class' => 'Helper_Hash',
                                    ),    'helperHeader'   => array(
        'class' => 'Helper_Header',
                                    ),    'helperImage'   => array(
        'class' => 'Helper_Image',
                                    ),    'helperImageResize'   => array(
        'class' => 'Helper_Image_Resize',
                                    ),    'helperJson'   => array(
        'class' => 'Helper_Json',
                                    ),    'helperLink'   => array(
        'class' => 'Helper_Link',
                                    ),    'helperMap'   => array(
        'class' => 'Helper_Map',
                                    ),    'helperMetagraphy'   => array(
        'class' => 'Helper_Metagraphy',
                                    ),    'helperMigration'   => array(
        'class' => 'Helper_Migration',
                                    ),    'helperMigrationLog'   => array(
        'class' => 'Helper_Migration_Log',
                                    ),    'helperMigrationMark'   => array(
        'class' => 'Helper_Migration_Mark',
                                    ),    'helperMigrationModel'   => array(
        'class' => 'Helper_Migration_Model',
                                'disableConstruct'      => true,
                    ),    'helperMigrationProcess'   => array(
        'class' => 'Helper_Migration_Process',
                                    ),    'helperMigrationQueue'   => array(
        'class' => 'Helper_Migration_Queue',
                                    ),    'helperMigrationSequence'   => array(
        'class' => 'Helper_Migration_Sequence',
                                    ),    'helperModel'   => array(
        'class' => 'Helper_Model',
                                    ),    'helperModelAcl'   => array(
        'class' => 'Helper_Model_Acl',
                                    ),    'helperModelAclAnnotation'   => array(
        'class' => 'Helper_Model_Acl_Annotation',
                                    ),    'helperModelAclConfig'   => array(
        'class' => 'Helper_Model_Acl_Config',
                                    ),    'helperModelAclSync'   => array(
        'class' => 'Helper_Model_Acl_Sync',
                                    ),    'helperModelAclTable'   => array(
        'class' => 'Helper_Model_Acl_Table',
                                    ),    'helperModelCollection'   => array(
        'class' => 'Helper_Model_Collection',
                                    ),    'helperModelCreate'   => array(
        'class' => 'Helper_Model_Create',
                                    ),    'helperModelEvent'   => array(
        'class' => 'Helper_Model_Event',
                                    ),    'helperModelImport'   => array(
        'class' => 'Helper_Model_Import',
                                    ),    'helperModelImportInput'   => array(
        'class' => 'Helper_Model_Import/input',
                        'args'  => array(
                        'cliInput'                    ),
                                'source'    => array(
                        'name'  => 'dataTransportManager',
                        'method'    => 'get',
                                )
            ),    'helperModelManager'   => array(
        'class' => 'Helper_Model_Manager',
                                    ),    'helperModelMigrateDiff'   => array(
        'class' => 'Helper_Model_Migrate_Diff',
                                    ),    'helperModelMigrateRebuild'   => array(
        'class' => 'Helper_Model_Migrate_Rebuild',
                                    ),    'helperModelMigrateSync'   => array(
        'class' => 'Helper_Model_Migrate_Sync',
                                    ),    'helperModelMissing'   => array(
        'class' => 'Helper_Model_Missing',
                                    ),    'helperModelOption'   => array(
        'class' => 'Helper_Model_Option',
                                    ),    'helperModelScheme'   => array(
        'class' => 'Helper_Model_Scheme',
                                    ),    'helperModelSchemeInput'   => array(
        'class' => 'Helper_Model_Scheme/input',
                        'args'  => array(
                        'cliInput'                    ),
                                'source'    => array(
                        'name'  => 'dataTransportManager',
                        'method'    => 'get',
                                )
            ),    'helperModelSync'   => array(
        'class' => 'Helper_Model_Sync',
                                    ),    'helperModelTable'   => array(
        'class' => 'Helper_Model_Table',
                                    ),    'helperMysql'   => array(
        'class' => 'Helper_Mysql',
                                    ),    'helperNetwork'   => array(
        'class' => 'Helper_Network',
                                    ),    'helperPlural'   => array(
        'class' => 'Helper_Plural',
                                    ),    'helperQueryTranslatorMysql'   => array(
        'class' => 'Helper_Query_Translator_Mysql',
                                    ),    'helperRouter'   => array(
        'class' => 'Helper_Router',
                                    ),    'helperSchedule'   => array(
        'class' => 'Helper_Schedule',
                                    ),    'helperService'   => array(
        'class' => 'Helper_Service',
                                    ),    'helperSiteLocation'   => array(
        'class' => 'Helper_Site_Location',
                                    ),    'helperString'   => array(
        'class' => 'Helper_String',
                                    ),    'helperTranslit'   => array(
        'class' => 'Helper_Translit',
                                    ),    'helperUnique'   => array(
        'class' => 'Helper_Unique',
                                    ),    'helperUrl'   => array(
        'class' => 'Helper_Url',
                                    ),    'helperViewResource'   => array(
        'class' => 'Helper_View_Resource',
                                    ),    'helperXml'   => array(
        'class' => 'Helper_Xml',
                                    ),    'helperYandexOriginalText'   => array(
        'class' => 'Helper_Yandex_Original_Text',
                                    ),    'htmlFormFieldManager'   => array(
        'class' => 'Html_Form_Field_Manager',
                                    ),    'htmlFormFieldSelectOptionManager'   => array(
        'class' => 'Html_Form_Field_Select_Option_Manager',
                                    ),    'htmlFormManager'   => array(
        'class' => 'Html_Form_Manager',
                                    ),    'loader'   => array(
        'class' => 'Loader',
                                    ),    'loaderAuto'   => array(
        'class' => 'Loader_Auto',
                                    ),    'loginzaParser'   => array(
        'class' => 'Loginza_Parser',
                                    ),    'mailMessage'   => array(
        'class' => 'Mail_Message',
                                    ),    'mailProvider'   => array(
        'class' => 'Mail_Provider',
                                    ),    'mailTemplate'   => array(
        'class' => 'Mail_Template',
                                    ),    'migrationManager'   => array(
        'class' => 'Migration_Manager',
                                    ),    'migrationSequence'   => array(
        'class' => 'Helper_Migration_Sequence/sequence',
                        'args'  => array(
                        'Increment'                    ),
                                'source'    => array(
                        'name'  => 'sequenceManager',
                        'method'    => 'get',
                                )
            ),    'modelCollectionProcessorManager'   => array(
        'class' => 'Model_Collection_Processor_Manager',
                                    ),    'modelCollectionProcessorPool'   => array(
        'class' => 'Model_Collection_Processor_Pool',
                                    ),    'modelEventManager'   => array(
        'class' => 'Model_Event_Manager',
                                    ),    'modelManager'   => array(
        'class' => 'Model_Manager',
                                    ),    'modelMapper'   => array(
        'class' => 'Model_Mapper',
                                    ),    'modelMapperReference'   => array(
        'class' => 'Model_Mapper_Reference',
                                    ),    'modelMapperScheme'   => array(
        'class' => 'Model_Mapper_Scheme',
                                'disableConstruct'      => true,
                    ),    'modelMapperSchemeRender'   => array(
        'class' => 'Model_Mapper_Scheme_Render',
                                    ),    'modelOptionManager'   => array(
        'class' => 'Model_Option_Manager',
                                    ),    'modelRepositoryManager'   => array(
        'class' => 'Model_Repository_Manager',
                                    ),    'modelScheme'   => array(
        'class' => 'Model_Scheme',
                                    ),    'moduleManager'   => array(
        'class' => 'Module_Manager',
                                    ),    'multipaginator'   => array(
        'class' => 'Multipaginator',
                                    ),    'pageTitle'   => array(
        'class' => 'Page_Title',
                                    ),    'pageTitleSpecificationManager'   => array(
        'class' => 'Page_Title_Specification_Manager',
                                    ),    'paginator'   => array(
        'class' => 'Paginator',
                                'disableConstruct'      => true,
                    ),    'postEditor'   => array(
        'class' => 'IU_Post_Editor',
                                'disableConstruct'      => true,
                    ),    'postEditorPool'   => array(
        'class' => 'IU_Post_Editor_Pool',
                                    ),    'query'   => array(
        'class' => 'Query',
                                        'source'    => array(
                        'method'    => 'instance',
                                )
            ),    'queryBuilder'   => array(
        'class' => 'Query',
                                        'source'    => array(
                        'method'    => 'instance',
                                )
            ),    'queryCommandBroker'   => array(
        'class' => 'Query_Command_Broker',
                                    ),    'queryCommandPool'   => array(
        'class' => 'Query_Command_Pool',
                                    ),    'queryTranslator'   => array(
        'class' => 'Query_Translator',
                                    ),    'registry'   => array(
        'class' => 'Registry',
                                    ),    'request'   => array(
        'class' => 'Request',
                                    ),    'resourceManager'   => array(
        'class' => 'Resource_Manager',
                                    ),    'route'   => array(
        'class' => 'Route',
                                    ),    'routeCache'   => array(
        'class' => 'Route/provider',
                        'args'  => array(
                        'Route_Cache'                    ),
                                'source'    => array(
                        'name'  => 'dataProviderManager',
                        'method'    => 'get',
                                )
            ),    'routeParamExtractorManager'   => array(
        'class' => 'Route_Param_Extractor_Manager',
                                    ),    'router'   => array(
        'class' => 'Router',
                                    ),    'sequenceManager'   => array(
        'class' => 'Sequence_Manager',
                                    ),    'serviceCodeAnalyze'   => array(
        'class' => 'Service_Code_Analyze',
                                    ),    'serviceDataTransport'   => array(
        'class' => 'Service_Data_Transport',
                                    ),    'serviceEmailBlacklist'   => array(
        'class' => 'Service_Email_Blacklist',
                                    ),    'serviceEventSlot'   => array(
        'class' => 'Service_Event_Slot',
                                    ),    'serviceHttpHeader'   => array(
        'class' => 'Service_Http_Header',
                                    ),    'serviceInjector'   => array(
        'class' => 'Service_Injector',
                                    ),    'serviceQueue'   => array(
        'class' => 'Service_Queue',
                                    ),    'serviceRoute'   => array(
        'class' => 'Service_Route',
                                    ),    'serviceStaticCssOptimizator'   => array(
        'class' => 'Service_Static_Css_Optimizator',
                                    ),    'serviceStaticSpriteOptimizator'   => array(
        'class' => 'Service_Static_Sprite_Optimizator',
                                    ),    'serviceUnsubscribe'   => array(
        'class' => 'Service_Unsubscribe',
                                    ),    'sessionManager'   => array(
        'class' => 'Session_Manager',
                                    ),    'sessionResource'   => array(
        'class' => 'Session_Resource',
                                'disableConstruct'      => true,
                    ),    'shutdownManager'   => array(
        'class' => 'Shutdown_Manager',
                                    ),    'staticFile'   => array(
        'class' => 'Static_File',
                                    ),    'staticSpriteManager'   => array(
        'class' => 'Static_Sprite_Manager',
                                    ),    'sync'   => array(
        'class' => 'Controller_Sync',
                                    ),    'tempContent'   => array(
        'class' => 'Temp_Content',
                                    ),    'unitOfWork'   => array(
        'class' => 'Unit_Of_Work',
                                    ),    'unitOfWorkManager'   => array(
        'class' => 'Unit_Of_Work_Manager',
                                    ),    'unitOfWorkSession'   => array(
        'class' => 'Unit_Of_Work_Session',
                                    ),    'user'   => array(
        'class' => 'User',
                                    ),    'userCli'   => array(
        'class' => 'User_Cli',
                                'disableConstruct'      => true,
                    ),    'userGuest'   => array(
        'class' => 'User_Guest',
                                'disableConstruct'      => true,
                    ),    'userLoginza'   => array(
        'class' => 'User_Loginza',
                                    ),    'userSession'   => array(
        'class' => 'User_Session',
                                'disableConstruct'      => true,
                    ),    'validatorErrorManager'   => array(
        'class' => 'Validator_Error_Manager',
                                    ),    'validatorManager'   => array(
        'class' => 'Validator_Manager',
                                    ),    'viewCacheFragmentManager'   => array(
        'class' => 'View_Cache_Fragment_Manager',
                                    ),    'viewHelperManager'   => array(
        'class' => 'View_Helper_Manager',
                                    ),    'viewRenderManager'   => array(
        'class' => 'View_Render_Manager',
                                    ),    'viewResourceManager'   => array(
        'class' => 'View_Resource_Manager',
                                    ),    'voManager'   => array(
        'class' => 'Vo_Manager',
                                    ));